version: 0.2
phases:
  pre_build:
    commands:
      ##### 環境変数の定義 ###################################
      - IMAGE_VERSION=7.6.23-1
      - REPOSITORY_URI=public.ecr.aws/g2o5x8c8
      - REPOSITORY_PATH=${REPOSITORY_URI}/draken/buildimage
      # ECRのリポジトリにログイン
      # publicリポジトリはprivateとは別コマンド。
      - aws ecr-public  get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}
  build:
    commands:
      - cd images
      - docker build -t ${REPOSITORY_PATH}:${IMAGE_VERSION} -f latest/Dockerfile .
      - docker push ${REPOSITORY_PATH}:${IMAGE_VERSION}
